# Generated by Django 2.0 on 2017-12-14 03:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cid',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False, verbose_name='CID')),
                ('contractname', models.CharField(max_length=255, verbose_name='客户合同名')),
                ('installname', models.CharField(default='东莞光联', max_length=50, verbose_name='安装名义')),
                ('sales', models.EmailField(max_length=254, verbose_name='业务员')),
                ('mrtg', models.CharField(blank=True, max_length=120, verbose_name='MRTG登入链接')),
                ('mrtgpass', models.CharField(blank=True, max_length=80, verbose_name='客户MRTG账号')),
                ('netflow', models.CharField(blank=True, max_length=120, verbose_name='Netflow登入链接')),
                ('netflowpass', models.CharField(blank=True, max_length=80, verbose_name='客户Netflow账号')),
                ('Apppass', models.CharField(blank=True, max_length=120, verbose_name='客户APP账号')),
                ('status', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('ON_TEST', '测试')], default='ON_TEST', max_length=8, verbose_name='客户状态')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
            options={
                'ordering': ['-cid'],
            },
        ),
        migrations.CreateModel(
            name='Fastline',
            fields=[
                ('fastid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='FastID')),
                ('fastpe', models.CharField(max_length=50, verbose_name='FastPE')),
                ('fastport', models.CharField(blank=True, max_length=20, verbose_name='接入端口')),
                ('fastwanip', models.CharField(blank=True, max_length=20, verbose_name='WAN_IP')),
                ('hkip', models.CharField(blank=True, max_length=255, verbose_name='HK_IP')),
                ('level', models.CharField(choices=[('MAIN', 'MAIN'), ('BACKUP', 'BACKUP')], default='MAIN', max_length=10, verbose_name='主/备类型')),
                ('bandwidth', models.CharField(max_length=50, verbose_name='频宽')),
                ('servicenumber', models.CharField(blank=True, max_length=24, verbose_name='公司服务编号')),
                ('status', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('ON_TEST', '测试')], default='ON_TEST', max_length=8, verbose_name='状态')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
            options={
                'ordering': ['-fastid'],
            },
        ),
        migrations.CreateModel(
            name='Fasttag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=50, verbose_name='标签名')),
                ('tagvalue', models.CharField(max_length=255, verbose_name='标签值')),
                ('tagcreate_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('tagmod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('fastid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tellme.Fastline')),
            ],
            options={
                'ordering': ['tagcreate_date'],
            },
        ),
        migrations.CreateModel(
            name='Flanline',
            fields=[
                ('flanid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='FlanID')),
                ('flanpe', models.CharField(max_length=50, verbose_name='FlanPE')),
                ('flanport', models.CharField(blank=True, max_length=20, verbose_name='接入端口')),
                ('flanwanip', models.CharField(blank=True, max_length=20, verbose_name='WAN_IP')),
                ('lanip', models.CharField(blank=True, max_length=255, verbose_name='LAN_IP')),
                ('level', models.CharField(choices=[('MAIN', 'MAIN'), ('BACKUP', 'BACKUP')], default='MAIN', max_length=10, verbose_name='主/备类型')),
                ('bandwidth', models.CharField(max_length=50, verbose_name='频宽')),
                ('servicenumber', models.CharField(blank=True, max_length=24, verbose_name='公司服务编号')),
                ('status', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('ON_TEST', '测试')], default='ON_TEST', max_length=8, verbose_name='状态')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
            options={
                'ordering': ['-flanid'],
            },
        ),
        migrations.CreateModel(
            name='Flantag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=50, verbose_name='标签名')),
                ('tagvalue', models.CharField(max_length=255, verbose_name='标签值')),
                ('tagcreate_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('tagmod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('flanid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tellme.Flanline')),
            ],
            options={
                'ordering': ['tagcreate_date'],
            },
        ),
        migrations.CreateModel(
            name='Jituan',
            fields=[
                ('jtid', models.IntegerField(primary_key=True, serialize=False, verbose_name='集团ID')),
                ('jtname', models.CharField(max_length=255, verbose_name='集团名称')),
                ('status', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('ON_TEST', '测试')], default='ON', max_length=8, verbose_name='状态')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='Localline',
            fields=[
                ('localid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='FlanID')),
                ('bandwidth', models.CharField(max_length=50, verbose_name='频宽')),
                ('localsp', models.CharField(blank=True, max_length=50, verbose_name='运营商')),
                ('localguard', models.CharField(blank=True, max_length=255, verbose_name='报障资料')),
                ('localaddra', models.CharField(blank=True, max_length=255, verbose_name='A端地址')),
                ('localaddrb', models.CharField(blank=True, max_length=255, verbose_name='B端地址')),
                ('servicenumber', models.CharField(blank=True, max_length=24, verbose_name='公司服务编号')),
                ('localnumber', models.CharField(blank=True, max_length=50, verbose_name='线路编号')),
                ('status', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('ON_TEST', '测试')], default='ON_TEST', max_length=8, verbose_name='状态')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
            options={
                'ordering': ['-localid'],
            },
        ),
        migrations.CreateModel(
            name='Localtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=50, verbose_name='标签名')),
                ('tagvalue', models.CharField(max_length=255, verbose_name='标签值')),
                ('tagcreate_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('tagmod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('localid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tellme.Localline')),
            ],
            options={
                'ordering': ['tagcreate_date'],
            },
        ),
        migrations.CreateModel(
            name='Monitorline',
            fields=[
                ('monitorid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='监控ID')),
                ('monitorobj', models.CharField(max_length=50, verbose_name='监控对象')),
                ('monitorip', models.CharField(max_length=20, verbose_name='监控IP')),
                ('status', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('ON_TEST', '测试')], default='ON_TEST', max_length=8, verbose_name='状态')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
            options={
                'ordering': ['-monitorid'],
            },
        ),
        migrations.CreateModel(
            name='Monitortag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=50, verbose_name='标签名')),
                ('tagvalue', models.CharField(max_length=255, verbose_name='标签值')),
                ('tagcreate_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('tagmod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('monitorid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tellme.Monitorline')),
            ],
            options={
                'ordering': ['tagcreate_date'],
            },
        ),
        migrations.CreateModel(
            name='Siline',
            fields=[
                ('siid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='SIID')),
                ('siname', models.CharField(max_length=50, verbose_name='SI名')),
                ('sicontent', models.CharField(blank=True, max_length=255, verbose_name='SI内容')),
                ('servicenumber', models.CharField(blank=True, max_length=24, verbose_name='公司服务编号')),
                ('status', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('ON_TEST', '测试')], default='ON_TEST', max_length=8, verbose_name='状态')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
            options={
                'ordering': ['-siid'],
            },
        ),
        migrations.CreateModel(
            name='Sitag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=50, verbose_name='标签名')),
                ('tagvalue', models.CharField(max_length=255, verbose_name='标签值')),
                ('tagcreate_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('tagmod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('siid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tellme.Siline')),
            ],
            options={
                'ordering': ['tagcreate_date'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('siteid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='SiteID')),
                ('sitename', models.CharField(max_length=255, verbose_name='站点名')),
                ('siteaddr', models.CharField(max_length=255, verbose_name='地址')),
                ('mastercontact', models.CharField(blank=True, max_length=20, verbose_name='主联络人')),
                ('masterphone', models.CharField(blank=True, max_length=20, verbose_name='主联络电话')),
                ('masteremail', models.EmailField(blank=True, max_length=254, verbose_name='主联络Email')),
                ('ocontacts', models.CharField(blank=True, max_length=255, verbose_name='其他联系信息')),
                ('status', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('ON_TEST', '测试')], default='ON_TEST', max_length=8, verbose_name='站点状态')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tellme.Cid')),
            ],
            options={
                'ordering': ['-siteid'],
            },
        ),
        migrations.AddField(
            model_name='siline',
            name='siteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tellme.Site'),
        ),
        migrations.AddField(
            model_name='monitorline',
            name='siteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tellme.Site'),
        ),
        migrations.AddField(
            model_name='localline',
            name='siteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tellme.Site'),
        ),
        migrations.AddField(
            model_name='flanline',
            name='siteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tellme.Site'),
        ),
        migrations.AddField(
            model_name='fastline',
            name='siteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tellme.Site'),
        ),
        migrations.AddField(
            model_name='cid',
            name='jtid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tellme.Jituan'),
        ),
    ]
