# Generated by Django 2.0 on 2017-12-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pm',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Psale',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='name')),
            ],
        ),
        migrations.RenameField(
            model_name='cid',
            old_name='Apppass',
            new_name='apppass',
        ),
        migrations.AlterField(
            model_name='fastline',
            name='servicenumber',
            field=models.CharField(blank=True, max_length=50, verbose_name='公司服务编号'),
        ),
        migrations.AlterField(
            model_name='flanline',
            name='servicenumber',
            field=models.CharField(blank=True, max_length=50, verbose_name='公司服务编号'),
        ),
        migrations.AlterField(
            model_name='localline',
            name='servicenumber',
            field=models.CharField(blank=True, max_length=50, verbose_name='公司服务编号'),
        ),
        migrations.AlterField(
            model_name='siline',
            name='servicenumber',
            field=models.CharField(blank=True, max_length=50, verbose_name='公司服务编号'),
        ),
    ]
