# Generated by Django 2.0 on 2017-12-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0002_auto_20171223_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noc',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='name')),
            ],
        ),
    ]
