# Generated by Django 2.0 on 2018-01-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0004_auto_20180110_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flanline',
            name='level',
        ),
        migrations.AddField(
            model_name='flanline',
            name='bkpe',
            field=models.CharField(blank=True, max_length=50, verbose_name='备PE'),
        ),
        migrations.AddField(
            model_name='flanline',
            name='bkport',
            field=models.CharField(blank=True, max_length=20, verbose_name='备接口'),
        ),
        migrations.AddField(
            model_name='flanline',
            name='bkwanip',
            field=models.CharField(blank=True, max_length=20, verbose_name='备WANIP'),
        ),
    ]
