# Generated by Django 2.0 on 2018-01-11 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0005_auto_20180110_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fastline',
            options={'ordering': ['-svcid']},
        ),
        migrations.AlterModelOptions(
            name='flanline',
            options={'ordering': ['-svcid']},
        ),
        migrations.AlterModelOptions(
            name='localline',
            options={'ordering': ['-svcid']},
        ),
        migrations.AlterModelOptions(
            name='monitorline',
            options={'ordering': ['-svcid']},
        ),
        migrations.AlterModelOptions(
            name='siline',
            options={'ordering': ['-svcid']},
        ),
        migrations.RenameField(
            model_name='fastline',
            old_name='fastid',
            new_name='svcid',
        ),
        migrations.RenameField(
            model_name='fasttag',
            old_name='fastid',
            new_name='svcid',
        ),
        migrations.RenameField(
            model_name='flanline',
            old_name='flanid',
            new_name='svcid',
        ),
        migrations.RenameField(
            model_name='flantag',
            old_name='flanid',
            new_name='svcid',
        ),
        migrations.RenameField(
            model_name='localline',
            old_name='localid',
            new_name='svcid',
        ),
        migrations.RenameField(
            model_name='localtag',
            old_name='localid',
            new_name='svcid',
        ),
        migrations.RenameField(
            model_name='monitorline',
            old_name='monitorid',
            new_name='svcid',
        ),
        migrations.RenameField(
            model_name='monitortag',
            old_name='monitorid',
            new_name='svcid',
        ),
        migrations.RenameField(
            model_name='siline',
            old_name='siid',
            new_name='svcid',
        ),
        migrations.RenameField(
            model_name='sitag',
            old_name='siid',
            new_name='svcid',
        ),
    ]
