# Generated by Django 2.0 on 2018-01-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0007_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=models.ImageField(upload_to='static/image'),
        ),
    ]
