# Generated by Django 2.0 on 2018-01-12 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0009_auto_20180112_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteimage',
            old_name='picture',
            new_name='imageurl',
        ),
    ]
