# Generated by Django 2.0 on 2018-01-15 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0010_auto_20180112_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期'),
        ),
        migrations.AddField(
            model_name='siteimage',
            name='uploader',
            field=models.CharField(blank=True, max_length=20, verbose_name='上传者'),
        ),
    ]
