# Generated by Django 2.0 on 2018-01-15 03:10

from django.db import migrations, models
import django.utils.timezone
import tellme.models


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0011_auto_20180115_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitereport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteid', models.CharField(max_length=20)),
                ('uploader', models.CharField(blank=True, max_length=20, verbose_name='上传者')),
                ('fileurl', models.FileField(upload_to=tellme.models.reporturl_handler)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
            ],
        ),
    ]
