# Generated by Django 2.0 on 2018-01-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0012_sitereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitereport',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
