# Generated by Django 2.0 on 2018-01-15 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tellme', '0013_sitereport_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalJituan',
            fields=[
                ('jtid', models.IntegerField(db_index=True, verbose_name='集团ID')),
                ('jtname', models.CharField(max_length=255, verbose_name='集团名称')),
                ('status', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('ON_TEST', 'ON_TEST')], default='ON', max_length=8, verbose_name='状态')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('mod_date', models.DateTimeField(blank=True, editable=False, verbose_name='最后修改日期')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical jituan',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
