# Generated by Django 2.0 on 2018-01-16 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0014_historicaljituan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaljituan',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalJituan',
        ),
    ]
