# Generated by Django 2.0 on 2018-01-17 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0015_auto_20180116_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traceentry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objname', models.CharField(max_length=20, verbose_name='对象名')),
                ('objpk', models.CharField(max_length=20, verbose_name='对象id')),
                ('type', models.CharField(max_length=10, verbose_name='类型')),
                ('context', models.CharField(max_length=255, verbose_name='内容')),
                ('oprater', models.CharField(max_length=30, verbose_name='操作人')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
            ],
        ),
        migrations.AlterModelOptions(
            name='fasttag',
            options={'ordering': ['create_date']},
        ),
        migrations.AlterModelOptions(
            name='flantag',
            options={'ordering': ['create_date']},
        ),
        migrations.AlterModelOptions(
            name='localtag',
            options={'ordering': ['create_date']},
        ),
        migrations.AlterModelOptions(
            name='monitortag',
            options={'ordering': ['create_date']},
        ),
        migrations.AlterModelOptions(
            name='sitag',
            options={'ordering': ['create_date']},
        ),
        migrations.RenameField(
            model_name='fasttag',
            old_name='tagcreate_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='fasttag',
            old_name='tagmod_date',
            new_name='mod_date',
        ),
        migrations.RenameField(
            model_name='flantag',
            old_name='tagcreate_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='flantag',
            old_name='tagmod_date',
            new_name='mod_date',
        ),
        migrations.RenameField(
            model_name='localtag',
            old_name='tagcreate_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='localtag',
            old_name='tagmod_date',
            new_name='mod_date',
        ),
        migrations.RenameField(
            model_name='monitortag',
            old_name='tagcreate_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='monitortag',
            old_name='tagmod_date',
            new_name='mod_date',
        ),
        migrations.RenameField(
            model_name='sitag',
            old_name='tagcreate_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='sitag',
            old_name='tagmod_date',
            new_name='mod_date',
        ),
    ]
