# Generated by Django 2.0 on 2018-01-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0016_auto_20180117_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceentry',
            name='context',
            field=models.TextField(verbose_name='内容'),
        ),
    ]
