# Generated by Django 2.0 on 2018-03-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0017_auto_20180117_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='localline',
            name='localname',
            field=models.CharField(blank=True, max_length=255, verbose_name='报障名义'),
        ),
        migrations.AlterField(
            model_name='localline',
            name='localguard',
            field=models.CharField(blank=True, max_length=255, verbose_name='报障信息'),
        ),
        migrations.AlterField(
            model_name='localline',
            name='svcid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
