# Generated by Django 2.0 on 2018-03-19 08:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0018_auto_20180314_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='NNIline',
            fields=[
                ('svcid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID')),
                ('pe', models.CharField(max_length=50, verbose_name='FlanPE')),
                ('port', models.CharField(blank=True, max_length=20, verbose_name='接口')),
                ('wanip', models.CharField(blank=True, max_length=20, verbose_name='WAN_IP')),
                ('servicenumber', models.CharField(blank=True, max_length=50, verbose_name='公司服务编号')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('siteid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tellme.Site')),
            ],
            options={
                'ordering': ['-svcid'],
            },
        ),
        migrations.CreateModel(
            name='NNItag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=50, verbose_name='标签名')),
                ('tagvalue', models.CharField(max_length=255, verbose_name='标签值')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('svcid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tellme.NNIline')),
            ],
            options={
                'ordering': ['create_date'],
            },
        ),
    ]
