# Generated by Django 2.0 on 2018-04-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0019_nniline_nnitag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traceentry',
            options={'ordering': ['-create_date']},
        ),
        migrations.AddField(
            model_name='nniline',
            name='bandwidth',
            field=models.CharField(blank=True, max_length=50, verbose_name='带宽'),
        ),
        migrations.AddField(
            model_name='nniline',
            name='nniaddr',
            field=models.CharField(blank=True, max_length=255, verbose_name='POP地址'),
        ),
        migrations.AddField(
            model_name='nniline',
            name='nniguard',
            field=models.CharField(blank=True, max_length=255, verbose_name='报障信息'),
        ),
        migrations.AddField(
            model_name='nniline',
            name='nniname',
            field=models.CharField(blank=True, max_length=255, verbose_name='报障名义'),
        ),
        migrations.AddField(
            model_name='nniline',
            name='nninumber',
            field=models.CharField(blank=True, max_length=50, verbose_name='线路编号'),
        ),
        migrations.AddField(
            model_name='nniline',
            name='nnisp',
            field=models.CharField(blank=True, max_length=50, verbose_name='运营商'),
        ),
    ]
