# Generated by Django 2.0 on 2018-04-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0020_auto_20180411_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nniline',
            name='pe',
            field=models.CharField(max_length=50, verbose_name='PE'),
        ),
    ]
