# Generated by Django 2.0 on 2018-04-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0021_auto_20180411_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastline',
            name='hkip',
            field=models.CharField(blank=True, max_length=2550, verbose_name='HK_IP'),
        ),
    ]
