# Generated by Django 2.0 on 2018-04-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0022_auto_20180411_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastline',
            name='hkip',
            field=models.CharField(blank=True, max_length=5120, verbose_name='HK_IP'),
        ),
    ]
