# Generated by Django 2.0 on 2018-04-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0023_auto_20180411_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastline',
            name='hkip',
            field=models.TextField(blank=True, verbose_name='HK_IP'),
        ),
    ]
